apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  selector:
    app: mlops-api
  ports:
    - name: metrics
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
