apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
  labels:
    app: mlops-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api
        image: gcr.io/modern-bond-175819/javiprietod/mlops-api:latest # <--- Reemplaza
        ports:
          - containerPort: 5000