apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: mlops-api-pod-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: mlops-api      # debe coincidir con el Deployment
  endpoints:
    - port: metrics       # nombre del port en el Deployment/Service
      path: /metrics
      interval: 30s
