apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-deployment
  labels:
    app: mlops-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web
  template:
    metadata:
      labels:
        app: mlops-web
    spec:
      containers:
        - name: mlops-web
          image: gcr.io/modern-bond-175819/mlops-api:latest
          ports:
          - containerPort: 8501
          env:
          - name: API_URL
            value: http://mlops-api-service:5000/predict 